try:
    print x
except:
    print 'error'

if 1:
    try:
        print x
    except:
        print 'error'

try:
    print x
except:
    print 'error'
finally:
    print 'done'
